name: "Lint and Format Code checking"

on:
  pull_request:
    branches:
      - main
jobs:
  lintAndFormat:
    runs-on: ubuntu-latest
    steps:
      # this clones the code from the PR
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run lint check
        run: npm run lint

      - name: Run format check
        run: npm run format

      - name: Run build check
        run: npm run build:check
